#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
systemctl status nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
curl http://54.89.193.243/

