#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i '/listen 80 default_server;/a listen 80;' /etc/nginx/sites-available/default
sudo sed -i '/listen \[::\]:80 default_server;/a listen [::]:80;' /etc/nginx/sites-available/default
systemctl status nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
curl http://54.89.193.243/

