#!/usr/bin/env bash

#program to perform a 301 move permanently
#redirect link containing replaceable string to google.com link instead

# script to install and setup nginx
sudo apt-get update
sudo apt-get install -y nginx

# update index.html file
echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name -;\n\trewrite ^\/redirect_me https:google\/\/google.com 301;"

# insert into the string
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart
