#!/usr/bin/env bash
# Configure web-01 to have HTTP response header

#First update the package list
sudo apt-get update
sudo apt-get install -y nginx

#Customize web server 2 to be like 1
echo "Hello World!" | sudo tee /var/www/html/index.html

#Perform a redirection to another page
new_string="server_name _; \n\trewrite ^\/redirect_me http:\/\/www.holbertonschool.com permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom error page for 404 status code
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Put the custom HTTP response header
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax errors
sudo nginx -t

#Restart the server
sudo service nginx restart
